# Generated by Django 4.0.4 on 2022-05-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=128, unique=True)),
                ('item_price', models.IntegerField(default=0)),
                ('descripton', models.TextField()),
                ('item_quantity', models.IntegerField(default=0)),
                ('item_sold', models.IntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
            ],
        ),
    ]
