# Generated by Django 4.0.4 on 2022-05-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='descripton',
            new_name='description',
        ),
    ]
